chan/urls.py
from django.conf.urls import url
from . import views


app_name = 'chan'
urlpatterns = [
    url(r'^$', views.show_messages, name = 'show_messages'),
    url(r'^reply/(?P<message_id>\d+)/', views.reply, name = 'reply'),
    url(r'^new_record/', views.new_record, name = 'new_record')
]

forum_chan/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chan/', include('chan.urls')),
]

chan/models.py
from django.db import models

# Create your models here.
from django.forms import ModelForm


class Message(models.Model):
    text_mess = models.TextField()
    pub_date = models.DateField()
    reply_to = models.ForeignKey("Message", null = True)

    def __str__(self):
        return self.text_mess


class MessageForm(ModelForm):
    class Meta:
        model = Message
        exclude = ['pub_date', 'reply_to']

chan/views.py
from django.utils import timezone

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from chan.models import Message, MessageForm


def show_messages(request):
    messages = Message.objects.all()
    context = {'messages' : messages,
               }
    #return HttpResponse("Тут будет лента сообщений")
    return render(request, "chan/show_messages.html", context)


def reply(request, message_id):
    message = Message.objects.get(pk=message_id)
    messages = Message.objects.filter(reply_to_id=message_id)
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            new_message = form.save(commit=False)
            new_message.pub_date = timezone.now()
            new_message.reply_to_id = message_id
            new_message.save()
            return redirect('/chan/reply/%s' %message_id)
    else:
        form = MessageForm()
    context = {'message': message,
               'form': form,
               'messages': messages}
    return render(request, 'chan/reply.html', context)

def new_record(request):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            new_message = form.save(commit=False)
            new_message.pub_date = timezone.now()
            new_message.save()
            return redirect('/chan/')
    else:
        form = MessageForm()
    return render(request, 'chan/new_record.html', {'form': form})

chan/templates/chan/new_record.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add record</title>
</head>
<body>
    <h2>Add record</h2>
    <form method="POST" action="{% url 'chan:new_record' %}">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Add">
    </form>
</body>
</html>

chan/templates/chan/reply.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reply</title>
</head>
<body>
<h1>Anonim №{{ message.id }}</h1>
{% for m in messages %}
    <div id="message{{ m.id }}">
        <p>Anonim №{{ m.id }} published on {{ m.pub_date }}</p>
        {% if m.reply_to_id != null %}
            <p>Reply to №{{ m.reply_to_id }}: <a href = "{% url 'chan:reply' m.reply_to_id %}">{{ m.reply_to }}</a></p>
        {% endif %}
        <p>Your message: <a href = "{% url 'chan:reply' m.id %}"> {{ m.text_mess }}</a></p>
        <hr/>
    </div>
{% endfor %}
<h2>Reply to №{{ message.id }} with message:"{{ message.text_mess }}"</h2>
<form method = "POST" action = "{% url 'chan:reply' message.id%}">
    {% csrf_token %}
    {{ form }}
    <input type = "submit" value = "Send reply">
</form>
<p><a href = "{% url 'chan:show_messages' %}">Return to the main page</a></p>
</body>
</html>

chan/templates/chan/show_messages.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List of Messages</title>
</head>
<body>
<h2>Hello, chan!!1</h2>
<h3><a href = "{% url 'chan:new_record' %}">Add new record</a></h3>
{% for m in messages %}
    <div id="message{{ m.id }}">
        <p>Anonim №{{ m.id }} published on {{ m.pub_date }}</p>
        {% if m.reply_to_id != null %}
            <p>Reply to №{{ m.reply_to_id }}: <a href = "{% url 'chan:reply' m.reply_to_id %}">{{ m.reply_to }}</a></p>
        {% endif %}
        <p>Your message: <a href = "{% url 'chan:reply' m.id %}">{{ m.text_mess }}</a></p>
        <hr/>
    </div>
{% endfor %}
</body>
</html>